### PR TITLE
[WIP] - DO NOT MERGE - validate haproxy22-2.2.23-1.el8.x86_64.rpm (4.11)

### PR DESCRIPTION
**Pull request by gcs278**
PR for soak testing haproxy22-2.2.23-1 (DO NOT MERGE)

### CODE REVIEW

**Comment by frobware** [comment]
CI was green.

/test all

**Comment by gcs278** [comment]
ipv6 null operator errors.
/test e2e-metal-ipi-ovn-ipv6

**Comment by gcs278** [comment]
Same null operator errors
/test e2e-metal-ipi-ovn-ipv6

**Comment by gcs278** [comment]
Same null operator errors
/test e2e-metal-ipi-ovn-ipv6

**Comment by gcs278** [comment]
Payload TRT tests look mostly good, except the last one looks to have a lot of failures. Doesn't appear to be related to haproxy.
/payload 4.11 nightly blocking

**Comment by gcs278** [comment]
We are moving on to testing haproxy 2.2.24

**Pull request closed without merging**
