### PR TITLE
[release-4.2] Bug 1809398: Dynamically reload metrics certificate/key file changes

### PR DESCRIPTION
**Pull request by marun**
Cherry-pick of #61. It didn't apply cleanly, the logging needed to be switched to glog for the release-4.2 branch.

/cc @ironcladlou

### CODE REVIEW

**Comment by ironcladlou** [comment]
@Miciah @frobware @danehans re: logging, not sure if I like the idea of a special patch because it's going to cause history divergence and liability if we need to pick other patches later. WDYT?

**Comment by marun** [comment]
> @Miciah @frobware @danehans re: logging, not sure if I like the idea of a special patch because it's going to cause history divergence and liability if we need to pick other patches later. WDYT?

I think history divergence between release and master branches is to be expected. If that wasn't the case, there would be no possibility of selective backport. 

Also, there's nothing precluding a revert of the bespoke patch in the future should it become a liability.

**Comment by ironcladlou** [comment]
Sounds like everyone's good with it, so

/approve

**Pull request merged**
