### PR TITLE
NE-1115: Update haproxy container builds to use haproxy 2.6

### PR DESCRIPTION
**Pull request by gcs278**
Update dockerfiles to use generic `haproxy` opposed to `haproxy22` so that the next container builds will use haproxy 2.6 which has been built via brew and checked in.

This will force the router to start using haproxy 2.6.

### CODE REVIEW

**Comment by Miciah** [comment]
@gcs278, [the ci/prow/images job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-images/1600290010626527232/artifacts/build-logs/haproxy-router.log) picked up the wrong HAProxy package:
```
2022-12-07T00:49:19.436300837Z ================================================================================
2022-12-07T00:49:19.436300837Z  Package          Arch       Version                 Repository            Size
2022-12-07T00:49:19.436300837Z ================================================================================
2022-12-07T00:49:19.436300837Z Installing:
2022-12-07T00:49:19.436300837Z  haproxy          x86_64     1.8.27-4.el8            rhel-8-appstream     1.4 M
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-images/1600290010626527232/artifacts/build-logs/haproxy-router.log

**Comment by gcs278** [comment]
/retest
CI failure don't look related. And haproxy is now 2.6.1 in[ ci/prow/images](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-images/1601225878493204480/artifacts/build-logs/haproxy-router.log) job.

**Comment by Miciah** [comment]
It looks better in [the last ci/prow/images run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-images/1601225878493204480):
```
2022-12-09T14:48:57.566569154Z ================================================================================
2022-12-09T14:48:57.566569154Z  Package          Arch       Version                Repository             Size
2022-12-09T14:48:57.566569154Z ================================================================================
2022-12-09T14:48:57.566569154Z Installing:
2022-12-09T14:48:57.566569154Z  haproxy26        x86_64     2.6.6-1.el8            rhel-8-server-ose     2.3 M
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-images/1601225878493204480/artifacts/build-logs/haproxy-router.log

**Comment by Miciah** [comment]
[e2e-agnosic failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-e2e-agnostic/1601273574985830400) because of a known issue affecting our CI on GCP.  
/test e2e-upgrade
/test e2e-aws-serial

**Comment by gcs278** [comment]
/retest
Unrelated flakes

**Comment by Miciah** [comment]
[e2e-aws-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-e2e-aws-serial/1601315897593565184) with an interesting failure:
```
{  AWS region: us-east-1 (zones: [ us-east-1a,us-east-1c ])
Using control plane instance type: m6a.xlarge
Using compute instance type: m6a.xlarge
W1209 20:50:53.590308      89 loader.go:223] Config not found: /tmp/kubeconfig-2787660912
info: Using registry public hostname registry.build01.ci.openshift.org
Saved credentials for registry.build01.ci.openshift.org
W1209 20:50:53.699898     101 loader.go:223] Config not found: /tmp/kubeconfig-2787660912
Error from server (Forbidden): imagestreams.image.openshift.io "release" is forbidden: User "system:serviceaccount:ci-op-wrnrwfl3:e2e-aws-serial" cannot get resource "imagestreams" in API group "image.openshift.io" in the namespace "ci-op-wrnrwfl3"
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-12-09T20:50:53Z"}
error: failed to execute wrapped command: exit status 1
}
```
/test e2e-aws-serial

[e2e-upgrade failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-e2e-upgrade/1601315897627119616) with some CNI failures:
```
ns/openshift-etcd pod/revision-pruner-7-ci-op-wrnrwfl3-9c2de-9gp9k-master-2 node/ci-op-wrnrwfl3-9c2de-9gp9k-master-2 - 404.20 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get network status for pod sandbox k8s_revision-pruner-7-ci-op-wrnrwfl3-9c2de-9gp9k-master-2_openshift-etcd_4682436d-7159-4f9c-a97f-fa60a6f28de9_0(47ea65a56a1085e67505fa7d3e493edc344ba4f429c8b9b23d6f88b336bf95fa): CNI network "" not found
ns/openshift-multus pod/network-metrics-daemon-29j6w node/ci-op-wrnrwfl3-9c2de-9gp9k-master-2 - never deleted - network rollout - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get network status for pod sandbox k8s_network-metrics-daemon-29j6w_openshift-multus_5f84ae8d-86ed-4fc9-bd70-af5efca66b8b_0(7dc160d667570479d3cd449bb0d1011ffb41df55ce3b9f19c2b8098af1124ebf): CNI network "" not found}
```
/test e2e-upgrade

[e2e-agnostic failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/430/pull-ci-openshift-router-master-e2e-agnostic/1601316034663419904) because of an issue with the gcp-cloud-credentials CredentialsRequest, which should be resolved by the workaround in https://github.com/openshift/machine-api-operator/pull/1097.
/test e2e-agnostic

**Comment by skrthomas** [comment]
docs ack

**Pull request merged**
