### PR TITLE
[WIP] DO NOT MERGE - soak test for haproxy-2.4.1 (EL8)

### PR DESCRIPTION
**Pull request by frobware**

### CODE REVIEW

**Comment by frobware** [comment]
```patch
From 5fe349897d9b28fcd8965d8a1e7daa321ed01b6e Mon Sep 17 00:00:00 2001
From: Andrew McDermott <amcdermo@redhat.com>
Date: Fri, 18 Jun 2021 16:51:40 +0100
Subject: [PATCH] Bump to 2.4.1

---
 .gitignore   | 1 +
 haproxy.spec | 7 +++++--
 sources      | 2 +-
 3 files changed, 7 insertions(+), 3 deletions(-)

diff --git a/.gitignore b/.gitignore
index 7e18d7f..3d26a4c 100644
--- a/.gitignore
+++ b/.gitignore
@@ -6,3 +6,4 @@
 /haproxy-2.0.19.tar.gz
 /haproxy-2.2.9.tar.gz
 /haproxy-2.2.13.tar.gz
+/haproxy-2.4.1.tar.gz
diff --git a/haproxy.spec b/haproxy.spec
index 17a2e7c..20c81f1 100644
--- a/haproxy.spec
+++ b/haproxy.spec
@@ -6,10 +6,10 @@
 
 %global _hardened_build 1
 
-%define real_name haproxy22
+%define real_name haproxy24
 
 Name:           haproxy
-Version:        2.2.13
+Version:        2.4.1
 Release:        1%{?dist}
 Summary:        Do not ship, install or use this, use %{real_name} subpackage instead
 
@@ -89,6 +89,9 @@ fi
 %{_sbindir}/%{name}
 
 %changelog
+* Fri Jun 18 2021 Andrew McDermott <amcdermo@redhat.com> - 2.4.1-1
+- Bump to 2.4.1
+
 * Tue Apr 20 2021 Andrew McDermott <amcdermo@redhat.com> - 2.2.13-1
 - Bump to 2.2.13
 
diff --git a/sources b/sources
index 1c2a043..4a253fd 100644
--- a/sources
+++ b/sources
@@ -1 +1 @@
-SHA512 (haproxy-2.2.13.tar.gz) = 33f0821b49e5916621d06cd524e25011072bfd0a9ed2db95a53c2d26f51ac484866fedbc54f2214b250f502297063926e6c5f6f4dee8aa77cde24098835c213d
+SHA512 (haproxy-2.4.1.tar.gz) = 6251f0ac77b7bceb349a174faff003bbe621490e5380dcdcd06bf712e13e0c94fd08a3651a62e68c862978031ca2fc9ac8432ea4c6062bb1c718db697030de9d
-- 
2.31.1
```

**Comment by frobware** [comment]
CI was green

/test e2e-agnostic

**Comment by alibo** [comment]
@frobware is this version going to be used in Openshift 4.9+ or there's still a chance we can see it in Openshift 4.8 release as well?

I'm asking this because RFC8441 is implemented in HAProxy 2.4+ and the issue with using Websocket and HTTP2 together is fixed in v2.4-dev7+:

https://github.com/haproxy/haproxy/issues/162

Related commits:
- https://github.com/haproxy/haproxy/commit/efe2276a9e9278f3832cfaeb54030155c4dc117f
- https://github.com/haproxy/haproxy/commit/7416274914671c47cdfb7834e551c30d2a6af495
- https://github.com/haproxy/haproxy/commit/f9dcbeeab3d2f92f92e98e7ebf95b72d0cc8b9d7
- https://github.com/haproxy/haproxy/commit/c9a0afcc321ec2830976334bd0bd868df32c9625
- https://github.com/haproxy/haproxy/commit/9bf957335e2c385b74901481f7a89c9565dfce53

**Comment by frobware** [comment]
https://github.com/openshift/router/pull/313 merged.

**Comment by frobware** [comment]
> @frobware is this version going to be used in Openshift 4.9+ or there's still a chance we can see it in Openshift 4.8 release as well?
> 
> I'm asking this because RFC8441 is implemented in HAProxy 2.4+ and the issue with using Websocket and HTTP2 together is fixed in v2.4-dev7+:
> 
> [haproxy/haproxy#162](https://github.com/haproxy/haproxy/issues/162)
> 
> Related commits:
> 
> * [haproxy/haproxy@efe2276](https://github.com/haproxy/haproxy/commit/efe2276a9e9278f3832cfaeb54030155c4dc117f)
> * [haproxy/haproxy@7416274](https://github.com/haproxy/haproxy/commit/7416274914671c47cdfb7834e551c30d2a6af495)
> * [haproxy/haproxy@f9dcbee](https://github.com/haproxy/haproxy/commit/f9dcbeeab3d2f92f92e98e7ebf95b72d0cc8b9d7)
> * [haproxy/haproxy@c9a0afc](https://github.com/haproxy/haproxy/commit/c9a0afcc321ec2830976334bd0bd868df32c9625)
> * [haproxy/haproxy@9bf9573](https://github.com/haproxy/haproxy/commit/9bf957335e2c385b74901481f7a89c9565dfce53)

Not a chance for 4.8. haproxy-2.4 has only just been released and, in fact, was released after both 4.8's feature- and code-freeze. https://github.com/openshift/router/pull/313 means haproxy-2.4.x is now in 4.9.

**Pull request closed without merging**
