### PR TITLE
images/router/haproxy: switch to haproxy 2.0

### PR DESCRIPTION
**Pull request by frobware**
Move to haproxy 2.x which is packaged here:

https://pkgs.devel.redhat.com/cgit/rpms/haproxy/log/?h=rhaos-4.4-rhel-7

### CODE REVIEW

**Comment by frobware** [comment]
See corresponding egress update: https://github.com/openshift/images/pull/14

**Comment by smarterclayton** [comment]
Can you run this test (e2e-aws) four or five times to watch for flakes?  I want to make sure we merge only after we’re reasonably confident flake rate is low.

**Comment by frobware** [comment]
> Can you run this test (e2e-aws) four or five times to watch for flakes? I want to make sure we merge only after we’re reasonably confident flake rate is low.

I have been doing it for a few weeks and haven't seen any. 

Today I just bumped [1] from haproxy from 2.0.10 -> 11 so will run the e2e-aws repeatedly today/tomorrow, or as soon as the updated RPM is available.

[1] https://pkgs.devel.redhat.com/cgit/rpms/haproxy/commit/?h=rhaos-4.4-rhel-7&id=327a389ecfb32f0e4c544b13e1f5e97bbbe4514c

**Comment by frobware** [comment]
```console
Pulling image docker-registry.default.svc:5000/ci-op-3czynjzb/pipeline@sha256:0ad2fa71e89910964369a4c825ce00cbda50ad2a9e728b2238f6133febbe012c ...
--> FROM docker-registry.default.svc:5000/ci-op-3czynjzb/pipeline@sha256:0ad2fa71e89910964369a4c825ce00cbda50ad2a9e728b2238f6133febbe012c as 0
--> RUN INSTALL_PKGS="haproxy20 rsyslog sysvinit-tools" &&     yum install -y $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir -p /var/lib/haproxy/router/{certs,cacerts,whitelists} &&     mkdir -p /var/lib/haproxy/{conf/.tmp,run,bin,log} &&     touch /var/lib/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config} &&     setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy &&     chown -R :0 /var/lib/haproxy &&     chmod -R g+w /var/lib/haproxy
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not receiving updates. You can use subscription-manager on the host to register and assign subscriptions.
http://base-4-4.ocp.svc/rhel-server-ose/repodata/5f4f7472ce0770f10ccaa1720f285b0623b84f43ec080cd3528fd24a044d98cb-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
```

Think this is transient as it occurred in https://github.com/openshift/images/pull/14 but the next 

/test/e2e-aws

was OK.

**Comment by frobware** [comment]
```console
2019/12/13 15:24:57 Building src
2019/12/13 15:24:57 Build src already succeeded in 27s
2019/12/13 15:24:57 Building base-router
2019/12/13 15:24:57 Build base-router already succeeded in 1m48s
2019/12/13 15:24:57 Building haproxy-router
2019/12/13 15:24:57 Building f5-router
2019/12/13 15:24:58 Build haproxy-router already succeeded in 1m15s
2019/12/13 15:24:58 Build f5-router already succeeded in 18s
2019/12/13 15:25:06 Tagging f5-router into stable
2019/12/13 15:25:06 Tagging haproxy-router into stable
2019/12/13 15:25:06 Create release image registry.svc.ci.openshift.org/ci-op-3czynjzb/release:latest
2019/12/13 15:26:02 Copied 2.18Mi of artifacts from release-latest to /logs/artifacts/release-latest
2019/12/13 15:26:02 Acquiring lease for "aws-quota-slice"
2019/12/13 15:26:48 Executing template e2e-aws
2019/12/13 15:26:48 Creating or restarting template instance
2019/12/13 15:26:48 Waiting for template instance to be ready
2019/12/13 15:26:50 Releasing lease for "aws-quota-slice"
2019/12/13 15:27:36 No custom metadata found and prow metadata already exists. Not updating the metadata.
2019/12/13 15:27:37 Ran for 2m39s
2019/12/13 15:27:37 Submitted failure event to sentry (id=2236c3b31bb9437bb8d95dcdbc1188b2)
error: could not run steps: step e2e-aws failed: could not wait for template instance to be ready: could not determine if template instance was ready: failed to create objects: object is being deleted: pods "e2e-aws" already exists
```

/retest

**Comment by frobware** [comment]
@smarterclayton I think that's one clean run today. Let's go for another...

/test e2e-aws

**Comment by frobware** [comment]
Another green CI @ Fri 13 Dec 21:48:51 GMT 2019

/test e2e-aws

**Comment by frobware** [comment]
Another green CI run. Starting another @ Sat 14 Dec 07:56:28 GMT 2019

/test e2e-aws

**Comment by frobware** [comment]
Another green CI run. Starting another @ Sat 14 Dec 2019 09:43:27 AM GMT

/test e2e-aws

**Comment by frobware** [comment]
Another green CI run. Starting another @ Sat 14 Dec 2019 12:13:37 PM GMT

**Comment by frobware** [comment]
Flake/fail:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/220/build-log.txt

```
[Feature:DeploymentConfig] deploymentconfigs adoption [Conformance] will orphan all RCs and adopt them back when recreated [Suite:openshift/conformance/parallel/minimal]
[Feature:OpenShiftControllerManager] TestDockercfgTokenDeletedController [Suite:openshift/conformance/parallel]
[Feature:Platform] Service Catalog should check basic usages: OCP-24062, OCP-24049, OCP-15600 [Suite:openshift/conformance/parallel]
[k8s.io] PrivilegedPod [NodeConformance] should enable privileged commands [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Dynamic PV (default fs)] subPath should be able to unmount after the subpath directory is deleted [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted [Suite:openshift/conformance/parallel] [Suite:k8s]

Failing tests:

[Feature:OpenShiftAuthorization] The default cluster RBAC policy should have correct RBAC rules [Suite:openshift/conformance/parallel]

Writing JUnit report to /tmp/artifacts/junit/junit_e2e_20191214-132107.xml

error: 7 fail, 919 pass, 1214 skip (25m56s)
2019/12/14 13:21:09 Container test in pod e2e-aws failed, exit code 1, reason Error
2019/12/14 13:29:05 Copied 228.35Mi of artifacts from e2e-aws to /logs/artifacts/e2e-aws
2019/12/14 13:29:05 Releasing lease for "aws-quota-slice"
2019/12/14 13:29:05 No custom metadata found and prow metadata already exists. Not updating the metadata.
2019/12/14 13:29:06 Ran for 1h14m33s
2019/12/14 13:29:06 Submitted failure event to sentry (id=4053d6acabc446769b42d9c4c7da3cd7)
error: could not run steps: step e2e-aws failed: template pod "e2e-aws" failed: the pod ci-op-nbfl5zpf/e2e-aws failed after 1h11m41s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
kx Container image "busybox:1.27" already present on machine
Dec 14 13:15:45.625 I persistentvolume/nfs-fptkx Recycler pod: Container image "busybox:1.27" already present on machine
Dec 14 13:15:45.801 I ns/default pod/recycler-for-nfs-fptkx Created container pv-recycler
Dec 14 13:15:45.809 I persistentvolume/nfs-fptkx Recycler pod: Created container pv-recycler (3 times)
Dec 14 13:15:45.831 I ns/default pod/recycler-for-nfs-fptkx Started container pv-recycler
Dec 14 13:15:45.838 I persistentvolume/nfs-fptkx Recycler pod: Started container pv-recycler (3 times)

W1214 13:20:48.230505     240 reflector.go:299] github.com/openshift/origin/pkg/monitor/operator.go:126: watch of *v1.ClusterOperator ended with: too old resource version: 138542 (138581)
Flaky tests:

[Feature:DeploymentConfig] deploymentconfigs adoption [Conformance] will orphan all RCs and adopt them back when recreated [Suite:openshift/conformance/parallel/minimal]
[Feature:OpenShiftControllerManager] TestDockercfgTokenDeletedController [Suite:openshift/conformance/parallel]
[Feature:Platform] Service Catalog should check basic usages: OCP-24062, OCP-24049, OCP-15600 [Suite:openshift/conformance/parallel]
[k8s.io] PrivilegedPod [NodeConformance] should enable privileged commands [LinuxOnly] [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Dynamic PV (default fs)] subPath should be able to unmount after the subpath directory is deleted [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted [Suite:openshift/conformance/parallel] [Suite:k8s]

Failing tests:

[Feature:OpenShiftAuthorization] The default cluster RBAC policy should have correct RBAC rules [Suite:openshift/conformance/parallel]

Writing JUnit report to /tmp/artifacts/junit/junit_e2e_20191214-132107.xml

error: 7 fail, 919 pass, 1214 skip (25m56s)
---
```

/test e2e-aws

**Comment by frobware** [comment]
Another green CI run. Starting another @ Sun 15 Dec 2019 10:59:34 AM GMT

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/222

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/223

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/224

/test aws-e2e

**Comment by frobware** [comment]
Another green CI run. Starting another @ Mon 16 Dec 2019 11:51:01 AM GMT

/test e2e-aws

**Comment by frobware** [comment]
Another green CI run. Starting another @ Mon 16 Dec 2019 01:21:12 PM GMT

/test e2e-aws

**Comment by ironcladlou** [comment]
/approve

@smarterclayton any objection to merging ASAP?

**Comment by ironcladlou** [comment]
/lgtm

@frobware will leave the hold until you're ready

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/227

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/228

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/229

/test e2e-aws

**Comment by frobware** [comment]
failures: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/231

/test e2e-aws

**Comment by frobware** [comment]
failures (5): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/232

/test e2e-aws

**Comment by frobware** [comment]
failures (9): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/233

/test e2e-aws

**Comment by frobware** [comment]
Summary as of `Tue 17 Dec 2019 06:05:17 PM GMT`:

Tests over the last 5 days:

**O**=OK, **X**=Failed

**OOOOOOXOXXOOXXXXX**

cc @smarterclayton @ironcladlou

**Comment by frobware** [comment]
failures (7): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/234

/test e2e-aws

**Comment by frobware** [comment]
failures (10): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/235

/test e2e-aws

**Comment by frobware** [comment]
failures (5): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/236

/test e2e-aws

**Comment by frobware** [comment]
```console
2019/12/18 14:00:00 Building src
2019/12/18 14:00:53 Build src succeeded after 53s
2019/12/18 14:01:00 Building base-router
2019/12/18 14:02:52 Build base-router failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-9sj3h31z/pipeline@sha256:f467cd9ad8eec87197b315538fe330876797e4560d0feeebf859364c841f3b62" ...
Replaced Dockerfile FROM image registry.svc.ci.openshift.org/openshift/origin-v4.0:base

Pulling image docker-registry.default.svc:5000/ci-op-9sj3h31z/pipeline@sha256:4bdb689e084a2febc9a35cfa4af64faec53bf12a6892336662e789ed06ffa719 ...

Pulling image registry.svc.ci.openshift.org/openshift/release:golang-1.12 ...
--> FROM registry.svc.ci.openshift.org/openshift/release:golang-1.12 as builder
--> WORKDIR /go/src/github.com/openshift/router
--> COPY . .
--> RUN make
CGO_ENABLED=0 GO111MODULE=on GOFLAGS=-mod=vendor go build -o openshift-router  -ldflags "-s -w -X github.com/openshift/router/pkg/version.versionFromGit="v0.0.0-unknown" -X github.com/openshift/router/pkg/version.commitFromGit="0617bdd" -X github.com/openshift/router/pkg/version.gitTreeState="clean" -X github.com/openshift/router/pkg/version.buildDate="2019-12-18T14:01:50Z" " github.com/openshift/router/cmd/openshift-router
error: build error: no such image
2019/12/18 14:02:56 No custom metadata found and prow metadata already exists. Not updating the metadata.
2019/12/18 14:02:58 Ran for 2m59s
2019/12/18 14:02:58 Submitted failure event to sentry (id=8739aa01695d4f68ab7391588bb6f087)
error: could not run steps: step base-router failed: could not wait for build: the build base-router failed after 1m52s with reason DockerBuildFailed: Docker build strategy has failed.

--> WORKDIR /go/src/github.com/openshift/router
--> COPY . .
--> RUN make
CGO_ENABLED=0 GO111MODULE=on GOFLAGS=-mod=vendor go build ...:01:50Z" " github.com/openshift/router/cmd/openshift-router
error: build error: no such image
```

/test e2e-aws

**Comment by frobware** [comment]
failures: (5) https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/238

/test e2e-aws

**Comment by frobware** [comment]
failures (3): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/71/pull-ci-openshift-router-master-e2e-aws/239

/test e2e-aws

**Pull request merged**
