### PR TITLE
[release-4.4] Bug 1879122: Backport haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant

### PR DESCRIPTION
**Pull request by sgreene570**
This PR is the 4.4 backport of #140 as per https://bugzilla.redhat.com/show_bug.cgi?id=1879122

---

rfc2616 and rfc7230 both demand that in HTTP messages lines be ended with CRLF.
Although both RFCs stipulate that LF-only line endings MAY or even SHOULD be accepted, It's better to be fully compliant. Very picky HTTP clients, such as web access firewalls, may trip over this and blame Openshift's router.
This PR is whitespace-only and converts all LF line terminators in this file to CRLF.

### CODE REVIEW

**Comment by Miciah** [comment]
Let's delete the "#184" in the title.
/title [release-4.4] Bug 1879122: Backport haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant

**Comment by sgreene570** [comment]
> Let's delete the "#184" in the title.

Whoops, copy-paste fail :facepalm: 
Thanks!

**Comment by Miciah** [comment]
Seems like I got the command wrong, and the bot didn't pick up the edit, so let's try again...
/retitle [release-4.4] Bug 1879122: Backport haproxy 503 error page: replace all LF by CRLF to be fully RFC compliant

**Pull request merged**
