### PR TITLE
RFE-3007: Add the ability to enabled option contstats

### PR DESCRIPTION
**Pull request by k-wall**

### CODE REVIEW

**Comment by candita** [comment]
RFE still on backlog
/hold

**Comment by candita** [comment]
RFE still on backlog

**Comment by Miciah** [comment]
/assign

Thanks!  Changes look good.
/approve
/lgtm

Since this PR is adding an option that is intended for now not to be exposed to end users, it does not need docs, PX, or QE.
/label docs-approved
/label px-approved
/label qe-approved

**Comment by Miciah** [comment]
[e2e-agnostic failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/449/pull-ci-openshift-router-master-e2e-agnostic/1681709162624454656) because `[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster should report telemetry` failed:
```
{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:365]: Unexpected error:
    <errors.aggregate | len:2, cap:2>: 
    [promQL query returned unexpected results:
    metricsclient_request_send{client="federate_to",job="telemeter-client",status_code="200"} >= 1
    [], promQL query returned unexpected results:
    federate_samples{job="telemeter-client"} >= 10
    []]
    [
        <*errors.errorString | 0xc001700240>{
            s: "promQL query returned unexpected results:\nmetricsclient_request_send{client=\"federate_to\",job=\"telemeter-client\",status_code=\"200\"} >= 1\n[]",
        },
        <*errors.errorString | 0xc0017003e0>{
            s: "promQL query returned unexpected results:\nfederate_samples{job=\"telemeter-client\"} >= 10\n[]",
        },
    ]
occurred
Ginkgo exit error 1: exit with code 1}
```
Let's see whether it's a flake.  
/test e2e-agnostic

**Pull request merged**
