### PR TITLE
OCPBUGS-13969: Bump vendors k8s libraries to 0.27.2

### PR DESCRIPTION
**Pull request by gcs278**
OCPBUGS-13969: Bump vendors k8s libraries to 0.27.2

```
go get k8s.io/api@v0.27.2
go get k8s.io/client-go@v0.27.2
go get k8s.io/apiserver@v0.27.2
go mod tidy
go mod vendor
```

Bump to go 1.20 due to dependency

### CODE REVIEW

**Comment by gcs278** [comment]
disruption test failed
/retest

**Comment by ShudiLi** [comment]
From QE side, tested it with 4.13.0-0.ci.test-2023-05-25-011455-ci-ln-lb5h4ik-latest
1.
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.ci.test-2023-05-25-011455-ci-ln-lb5h4ik-latest   True        False         36m     Cluster version is 4.13.0-0.ci.test-2023-05-25-011455-ci-ln-lb5h4ik-latest
% 

2.
% oc -n openshift-ingress rsync router-default-669655c86f-l57lw:/usr/bin/openshift-router .
% go version -m openshift-router                        
openshift-router: go1.20.3
	path	github.com/openshift/router/cmd/openshift-router
	mod	github.com/openshift/router	(devel)	
	dep	github.com/MakeNowJust/heredoc	v0.0.0-20171113091838-e9091a26100e	
	dep	github.com/NYTimes/gziphandler	v1.1.1	
	dep	github.com/antlr/antlr4/runtime/Go/antlr	v1.4.10	
	dep	github.com/asaskevich/govalidator	v0.0.0-20190424111038-f61b66f89f4a	
	dep	github.com/bcicen/go-haproxy	v0.0.0-20180203142132-ff5824fe38be	
	dep	github.com/beorn7/perks	v1.0.1	
	dep	github.com/blang/semver/v4	v4.0.0	
	dep	github.com/cenkalti/backoff/v4	v4.1.3	
	dep	github.com/cespare/xxhash/v2	v2.1.2	
	dep	github.com/cockroachdb/cmux	v0.0.0-20170110192607-30d10be49292	
	dep	github.com/coreos/go-semver	v0.3.0	
	dep	github.com/coreos/go-systemd/v22	v22.4.0	
	dep	github.com/davecgh/go-spew	v1.1.1	
	dep	github.com/emicklei/go-restful/v3	v3.9.0	
	dep	github.com/evanphx/json-patch	v4.12.0+incompatible	
	dep	github.com/felixge/httpsnoop	v1.0.3	
	dep	github.com/fsnotify/fsnotify	v1.6.0	
	dep	github.com/go-logr/logr	v1.2.3	
	dep	github.com/go-logr/stdr	v1.2.2	
	dep	github.com/go-openapi/jsonpointer	v0.19.6	
	dep	github.com/go-openapi/jsonreference	v0.20.1	
	dep	github.com/go-openapi/swag	v0.22.3	
	dep	github.com/gocarina/gocsv	v0.0.0-20190927101021-3ecffd272576	
	dep	github.com/gogo/protobuf	v1.3.2	
	dep	github.com/golang/groupcache	v0.0.0-20210331224755-41bb18bfe9da	
	dep	github.com/golang/protobuf	v1.5.3	
	dep	github.com/google/cel-go	v0.12.6	
	dep	github.com/google/gnostic	v0.5.7-v3refs	
	dep	github.com/google/go-cmp	v0.5.9	
	dep	github.com/google/gofuzz	v1.2.0	
	dep	github.com/google/uuid	v1.3.0	
	dep	github.com/grpc-ecosystem/go-grpc-prometheus	v1.2.0	
	dep	github.com/grpc-ecosystem/grpc-gateway/v2	v2.7.0	
	dep	github.com/imdario/mergo	v0.3.7	
	dep	github.com/josharian/intern	v1.0.0	
	dep	github.com/json-iterator/go	v1.1.12	
	dep	github.com/mailru/easyjson	v0.7.7	
	dep	github.com/matttproud/golang_protobuf_extensions	v1.0.2	
	dep	github.com/mitchellh/mapstructure	v1.4.1	
	dep	github.com/modern-go/concurrent	v0.0.0-20180306012644-bacd9c7ef1dd	
	dep	github.com/modern-go/reflect2	v1.0.2	
	dep	github.com/munnerz/goautoneg	v0.0.0-20191010083416-a7dc8b61c822	
	dep	github.com/openshift/api	v0.0.0-20230120195050-6ba31fa438f2	
	dep	github.com/openshift/client-go	v0.0.0-20230120202327-72f107311084	
	dep	github.com/openshift/library-go	v0.0.0-20230120202744-256994f916c4	
	dep	github.com/pkg/errors	v0.9.1	
	dep	github.com/pkg/profile	v1.3.0	
	dep	github.com/prometheus/client_golang	v1.14.0	
	dep	github.com/prometheus/client_model	v0.3.0	
	dep	github.com/prometheus/common	v0.37.0	
	dep	github.com/prometheus/procfs	v0.8.0	
	dep	github.com/sirupsen/logrus	v1.9.0	
	dep	github.com/spf13/cobra	v1.6.0	
	dep	github.com/spf13/pflag	v1.0.5	
	dep	github.com/stoewer/go-strcase	v1.2.0	
	dep	go.etcd.io/etcd/api/v3	v3.5.7	
	dep	go.etcd.io/etcd/client/pkg/v3	v3.5.7	
	dep	go.etcd.io/etcd/client/v3	v3.5.7	
	dep	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc	v0.35.0	
	dep	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp	v0.35.1	
	dep	go.opentelemetry.io/otel	v1.10.0	
	dep	go.opentelemetry.io/otel/exporters/otlp/internal/retry	v1.10.0	
	dep	go.opentelemetry.io/otel/exporters/otlp/otlptrace	v1.10.0	
	dep	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc	v1.10.0	
	dep	go.opentelemetry.io/otel/metric	v0.31.0	
	dep	go.opentelemetry.io/otel/sdk	v1.10.0	
	dep	go.opentelemetry.io/otel/trace	v1.10.0	
	dep	go.opentelemetry.io/proto/otlp	v0.19.0	
	dep	go.uber.org/atomic	v1.7.0	
	dep	go.uber.org/multierr	v1.6.0	
	dep	go.uber.org/zap	v1.19.0	
	dep	golang.org/x/crypto	v0.1.0	
	dep	golang.org/x/net	v0.8.0	
	dep	golang.org/x/oauth2	v0.0.0-20220411215720-9780585627b5	
	dep	golang.org/x/sync	v0.1.0	
	dep	golang.org/x/sys	v0.6.0	
	dep	golang.org/x/term	v0.6.0	
	dep	golang.org/x/text	v0.8.0	
	dep	golang.org/x/time	v0.0.0-20220210224613-90d013bbcef8	
	dep	google.golang.org/genproto	v0.0.0-20220502173005-c8bf987b8c21	
	dep	google.golang.org/grpc	v1.51.0	
	dep	google.golang.org/protobuf	v1.28.1	
	dep	gopkg.in/inf.v0	v0.9.1	
	dep	gopkg.in/natefinch/lumberjack.v2	v2.0.0	
	dep	gopkg.in/yaml.v2	v2.4.0	
	dep	gopkg.in/yaml.v3	v3.0.1	
	dep	k8s.io/api	v0.27.2	
	dep	k8s.io/apimachinery	v0.27.2	
	dep	k8s.io/apiserver	v0.27.2	
	dep	k8s.io/client-go	v0.27.2	
	dep	k8s.io/component-base	v0.27.2	
	dep	k8s.io/klog/v2	v2.90.1	
	dep	k8s.io/kms	v0.27.2	
	dep	k8s.io/kube-openapi	v0.0.0-20230501164219-8b0f38b5fd1f	
	dep	k8s.io/utils	v0.0.0-20230209194617-a36077c30491	
	dep	sigs.k8s.io/apiserver-network-proxy/konnectivity-client	v0.1.2	
	dep	sigs.k8s.io/json	v0.0.0-20221116044647-bc3834ca7abd	
	dep	sigs.k8s.io/structured-merge-diff/v4	v4.2.3	
	dep	sigs.k8s.io/yaml	v1.3.0	
	build	-buildmode=exe
	build	-compiler=gc
	build	-ldflags="-s -w -X github.com/openshift/router/pkg/version.versionFromGit=v0.0.0-unknown -X github.com/openshift/router/pkg/version.commitFromGit=2439bd05 -X github.com/openshift/router/pkg/version.gitTreeState=dirty -X github.com/openshift/router/pkg/version.buildDate=2023-05-25T01:08:57Z "
	build	CGO_ENABLED=1
	build	CGO_CFLAGS=
	build	CGO_CPPFLAGS=
	build	CGO_CXXFLAGS=
	build	CGO_LDFLAGS=
	build	GOARCH=amd64
	build	GOOS=linux
	build	GOAMD64=v1
	build	vcs=git
	build	vcs.revision=2439bd053c5e7302d32059f5b294bf19cf62d483
	build	vcs.time=2023-05-22T16:40:06Z
	build	vcs.modified=true

/label qe-approved
thanks

**Pull request merged**
