### PR TITLE
OCPBUGS-38426: DO NOT MERGE: validate haproxy22-2.2.24-5.rhaos4.13.el8.x86_64.rpm

### PR DESCRIPTION
**Pull request by gcs278**
/hold
/wip

### CODE REVIEW

**Comment by gcs278** [comment]
Everything worked first round.
/test all

**Comment by gcs278** [comment]
2nd test run success:
/test all

**Comment by gcs278** [comment]
One more round for sanity:
/test all

**Comment by alebedev87** [comment]
It's a pity `e0c9008874b89621449f7ff3e9bc6db4e94fac6d BUG/MINOR: h2: reject more chars from the :path pseudo header`commit didn't mention `b12ab9c04 MINOR: ist: Add istend() function to return a pointer to the end of the string` as a dependency along with the others. Should we do it in our patch or we don't do it in haproxy distgit and [Jira comment](https://issues.redhat.com/browse/OCPBUGS-39119?focusedId=25489157&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25489157)  is enough?

**Comment by alebedev87** [comment]
> Right, it's a pity, but I don't think we should edit the commit message, I think we should still take the commit as-is to avoid confusion. I think leaving a paper (comment) trail in the Jira is sufficient.

I thought of a README file rather the commit message. But I think Jira ticket reference (which is already there) is indeed enough.

**Comment by gcs278** [comment]
See [comment](https://issues.redhat.com/browse/OCPBUGS-39119?focusedId=25513826&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25513826)
/close

**Pull request closed without merging**
