### PR TITLE
[WIP] - DO NOT MERGE - validate-haproxy26-2.6.13-1 (OCP 4.12)

### PR DESCRIPTION
**Pull request by frobware**
This is deliberately using the RPM from OCP 4.14.

### CODE REVIEW

**Comment by neisw** [comment]
@frobware overall things look good.  I don't see the segfault issue.

 [ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade/1654538046952968192) results look good, each of the individual runs passed (ignore the aggregation since we only ran 5 jobs).

[ci-4.12-upgrade-from-stable-4.11-e2e-azure-sdn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade/1654538046952968192) is good overall (again look at the individual jobs under job-run-summary for aggregated) only thing to monitor is the disruption.  We see that in Azure as is so we will just need to monitor for 4.14 and make sure it doesn't look worse when we try to bring this in.

**Comment by frobware** [comment]
> @frobware overall things look good. I don't see the segfault issue.

Any chance the sample size is too small?

**Comment by frobware** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade 10
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-azure-sdn-upgrade 10

**Comment by frobware** [comment]
Closing as I'm going to concentrate testing on 4.13 and 4.14 only.

**Pull request closed without merging**
