### PR TITLE
Fixes #419: Allow configuration of haproxy option persist

### LINKED ISSUE #419: Allow configuration of haproxy option persist
Currently it is not possible to configure the haproxy backend option persist.

Informations can be found under [http://docs.haproxy.org/2.2/configuration.html#option persist](http://docs.haproxy.org/2.2/configuration.html#option%20persist)

Ideally this should be possible per route.

### PR DESCRIPTION
**Pull request by thomaswoeckinger**

### CODE REVIEW

**Comment by frobware** [comment]
As this would be new functionality please can you file an RFE under https://issues.redhat.com/projects/RFE/issues with the "Network Edge" component. PM and engineering meet regularly to discuss all RFEs.

**Comment by thomaswoeckinger** [comment]
> As this would be new functionality please can you file an RFE under https://issues.redhat.com/projects/RFE/issues with the "Network Edge" component. PM and engineering meet regularly to discuss all RFEs.

@frobware 
After login, when clicking the create button it is not possible to create an issue for the project `Openshift Request for Enhancement`. There is also no Project `Network Edge` or similar available.

Maybe i do not have permissions for that projects?

**Comment by thomaswoeckinger** [comment]
@Miciah Can you change the permissions to `Openshift Request for Enhancement` so that i can create an RFE?

**Comment by candita** [comment]
@thomaswoeckinger Thank you for the PR.  As @frobware mentioned, this looks like a new feature.  We have a new RFE process, so will look into why can't use it, but in the meantime:

We need a better description in this PR, and annotation unit testing in TestConfigTemplate, see https://github.com/openshift/router/blob/master/pkg/router/router_test.go#L181

Would you be willing to make a PR to add documentation for the new annotation? Route annotations are documented here: https://github.com/openshift/openshift-docs/blob/main/modules/nw-route-specific-annotations.adoc

**Comment by thomaswoeckinger** [comment]
> @thomaswoeckinger Thank you for the PR. As @frobware mentioned, this looks like a new feature. We have a new RFE process, so will look into why can't use it, but in the meantime:
> 
> We need a better description in this PR, and annotation unit testing in TestConfigTemplate, see https://github.com/openshift/router/blob/master/pkg/router/router_test.go#L181
> 
I will add one

> Would you be willing to make a PR to add documentation for the new annotation? Route annotations are documented here: https://github.com/openshift/openshift-docs/blob/main/modules/nw-route-specific-annotations.adoc

I will add some documentation to.

**Comment by thomaswoeckinger** [comment]
@Miciah , @frobware , @candita due to testing i found out that the router will remove a server entry from the backend as soon as the EndpointSlice is marked as ready state 'false' even if serving state is 'true'.
Instead a `set server <backend>/<server> state drain`should be issued on the router.
Can you tell me an code entry point where it is possible to issue such a command?

**Comment by candita** [comment]
> @Miciah , @frobware , @candita due to testing i found out that the router will remove a server entry from the backend as soon as the EndpointSlice is marked as ready state 'false' even if serving state is 'true'. Instead a `set server <backend>/<server> state drain`should be issued on the router. Can you tell me an code entry point where it is possible to issue such a command?

@thomaswoeckinger we will get in touch regarding the next steps on this one.  It's possible that this will require a RFE and enhancement document.

**Comment by thomaswoeckinger** [comment]
Added test case for the new option, as the used parser does not support retrieval of option attribute at the moment, i had to check it by simple old string parsing

**Comment by thomaswoeckinger** [comment]
@Miciah @candita @frobware Added a pull request for the documentation https://github.com/openshift/openshift-docs/pull/52923

**Comment by thomaswoeckinger** [comment]
@Miciah The two failing test jobs are not related to the changes as far as i see

**Comment by thomaswoeckinger** [comment]
@Miciah @candita @frobware anything new?

**Comment by thomaswoeckinger** [comment]
@Miciah @candita @frobware ping

**Comment by thomaswoeckinger** [comment]
> As this would be new functionality please can you file an RFE under https://issues.redhat.com/projects/RFE/issues with the "Network Edge" component. PM and engineering meet regularly to discuss all RFEs.

Can you tell me the project to use.

**Comment by thomaswoeckinger** [comment]
> As this would be new functionality please can you file an RFE under https://issues.redhat.com/projects/RFE/issues with the "Network Edge" component. PM and engineering meet regularly to discuss all RFEs.

I still can not create an issue because when i click 'create' there is no project RFE or 'Openshift Request for Enhancement' available i use thomas.woeckinger@gmail.com as login

**Pull request closed without merging**
