### PR TITLE
Bug 1957584: Revert 'Bug 1896977: Enhance host name validation in router'

### PR DESCRIPTION
**Pull request by Miciah**
#### Revert "Bug 1925697: Route admission should not use the override"

This reverts commit 62fa99cc5e53192542f58505d964cd1084bae6e6.

#### Revert "Bug 1896977: Enhance host name validation in router"

This reverts commit 7a106ecfaa40b3cbcc78728935871d91de94b299.

### CODE REVIEW

**Comment by quarterpin** [comment]
/lgtm
/label qe-approved

Verified via pre-merge verification workflow, more reference related to the test can be found in:
https://bugzilla.redhat.com/show_bug.cgi?id=1957584#c15

**Comment by Miciah** [comment]
Let's see if the title is causing this error:

    STEP 2: ENV "BUILD_LOGLEVEL"="0" "CLONEREFS_OPTIONS"="{\"src_root\":\"/go\",\"log\":\"/dev/null\",\"git_user_name\":\"ci-robot\",\"git_user_email\":\"ci-robot@openshift.io\",\"refs\":[{\"org\":\"openshift\",\"repo\":\"router\",\"repo_link\":\"https://github.com/openshift/router\",\"base_ref\":\"master\",\"base_sha\":\"c7b3985da3d1341fdac33f4d6bb6994fe29d32b7\",\"base_link\":\"https://github.com/openshift/router/commit/c7b3985da3d1341fdac33f4d6bb6994fe29d32b7\",\"pulls\":[{\"number\":290,\"author\":\"Miciah\",\"sha\":\"c9b4e183f3f96562ef8db024b53707ac2196dd19\",\"title\":\"Bug 1957584: Revert \\\"Bug 1896977: Enhance host name validation in router\\\"\",\"link\":\"https://github.com/openshift/router/pull/290\",\"commit_link\":\"https://github.com/openshift/router/pull/290/commits/c9b4e183f3f96562ef8db024b53707ac2196dd19\",\"author_link\":\"https://github.com/Miciah\"}]}],\"fail\":true}"
    STEP 3: ADD ./clonerefs /clonerefs
    STEP 4: RUN umask 0002 && /clonerefs && find /go/src -type d -not -perm -0775 | xargs --max-procs 10 --max-args 100 --no-run-if-empty chmod g+xw
    time="2021-05-27T04:29:09Z" level=warning msg="Path \"/run/secrets/etc-pki-entitlement\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
    time="2021-05-27T04:29:09Z" level=warning msg="Path \"/run/secrets/redhat.repo\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
    {"component":"clonerefs","file":"prow/cmd/clonerefs/main.go:32","func":"main.main","level":"fatal","msg":"Could not resolve options: could not load config from JSON var CLONEREFS_OPTIONS: invalid character 'B' after object key:value pair","severity":"fatal","time":"2021-05-27T04:29:09Z"}

/retitle Bug 1957584: Revert "Enhance host name validation in router"

**Comment by Miciah** [comment]
Now it's this:

    {"component":"clonerefs","file":"prow/cmd/clonerefs/main.go:32","func":"main.main","level":"fatal","msg":"Could not resolve options: could not load config from JSON var CLONEREFS_OPTIONS: invalid character 'E' after object key:value pair","severity":"fatal","time":"2021-05-27T04:37:27Z"}

Maybe without the double-quotes?

/retitle Bug 1957584: Revert 'Bug 1896977: Enhance host name validation in router'

**Pull request merged**
