### PR TITLE
NE-1304: container builds: switch to haproxy26 package

### PR DESCRIPTION
**Pull request by frobware**
https://issues.redhat.com/browse/NE-1304

### CODE REVIEW

**Comment by dgoodwin** [comment]
Needs lgtm and approved before we can get this merged.

**Comment by frobware** [comment]
- haproxy 2.6.13 bump now pushed: https://pkgs.devel.redhat.com/cgit/rpms/haproxy/commit/?h=rhaos-4.14-rhel-8&id=f764a5f6dda453173d8e41b5fffda7e4fac9576a
- RPM brew build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=53070151

Waiting for 2.6.13-1 RPM to turn up in https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.14/stream/el8/latest/x86_64/os/Packages/

**Comment by frobware** [comment]
RPM haproxy-2.6.13-1.rhaos4.14.el8__x86_64 now available in https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.14/stream/el8/latest/x86_64/os/Packages/

/hold cancel

**Comment by frobware** [comment]
/hold

Trying to understand why the build is using "haproxy-2.6.12", because it should be "2.6.13" as listed in https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.14/stream/el8/latest/x86_64/os/Packages/.


| RPM | date |
------| ---- |
| haproxy-2.6.13-1.rhaos4.14.el8__x86_64 | 05-Jun-2023 11:40  | 

The [build log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_router/487/pull-ci-openshift-router-master-images/1665704631604350976/artifacts/build-logs/haproxy-router.log) shows:

```console
7 matches for "2.6.12" in buffer: xxx
    100:2023-06-05T13:05:47.455127563Z  haproxy26      x86_64    2.6.12-1.rhaos4.14.el8     rhel-8-server-ose    2.3 M
    118:2023-06-05T13:05:47.987796323Z (5/5): haproxy26-2.6.12-1.rhaos4.14.el8.x86_64. 6.3 MB/s | 2.3 MB     00:00    
    135:2023-06-05T13:05:48.494729002Z   Running scriptlet: haproxy26-2.6.12-1.rhaos4.14.el8.x86_64                5/5 
    136:2023-06-05T13:05:48.857053711Z   Installing       : haproxy26-2.6.12-1.rhaos4.14.el8.x86_64                5/5 
    137:2023-06-05T13:05:48.865376818Z   Running scriptlet: haproxy26-2.6.12-1.rhaos4.14.el8.x86_64                5/5 
    142:2023-06-05T13:05:48.950051787Z   Verifying        : haproxy26-2.6.12-1.rhaos4.14.el8.x86_64                5/5 
    146:2023-06-05T13:05:49.167100324Z   haproxy26-2.6.12-1.rhaos4.14.el8.x86_64     libestr-0.1.10-1.el8.x86_64      
```

**Comment by frobware** [comment]
/hold cancel

2.6.13-1 RPM now available.

**Comment by frobware** [comment]
3 failures to create the sandbox

/retest-required

**Pull request merged**
