### PR TITLE
[WIP] Experiment with haproxy-2.1.x - DO NOT MERGE

### PR DESCRIPTION
**Pull request by frobware**

### CODE REVIEW

**Comment by smarterclayton** [comment]
I love CI

**Comment by frobware** [comment]
Huzzah - 2.1 is golden. :)

**Comment by smarterclayton** [comment]
Interesting warning in

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_router/74/pull-ci-openshift-router-master-e2e-aws/245/artifacts/e2e-aws/pods/openshift-ingress_router-default-69b875698d-ldhcd_router.log

```
I1220 18:11:34.593222       1 router.go:548] template "level"=0 "msg"="router reloaded"  "output"=" - Proxy protocol on, checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
E1220 18:11:39.611062       1 limiter.go:140] error reloading router: waitid: no child processes
 - Proxy protocol on, checking http://localhost:80 ...
 - Health check ok : 0 retry attempt(s).
```

Why is it exiting?  Either we should be eating that (harmless) or haproxy is dropping out on us.

Also, we really need to get the "upgrade without dropping connections" test in place if it isn't already - that's the #1 regression we can hit.

**Comment by frobware** [comment]
On `Thu 02 Jan 2020 12:56:55 PM GMT` CI is green with first run using `haproxy-2.1.2`.

**Comment by frobware** [comment]
Wait for `haproxy20-2.0.12` to turn up here[1]; once it does I'll test again then close this.

[1] http://download.eng.bos.redhat.com/rcm-guest/puddles/RHAOS/AtomicOpenShift/4.4/latest/x86_64/os/Packages/

**Comment by frobware** [comment]
> Why is it exiting? Either we should be eating that (harmless) or haproxy is dropping out on us.

Investigating this now.

**Comment by frobware** [comment]
> Investigating this now.



> > Why is it exiting? Either we should be eating that (harmless) or haproxy is dropping out on us.
> 
> Investigating this now.

Also see this with haproxy-2.0.12 in https://github.com/openshift/router/pull/77

```console
http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
I0106 19:12:45.658422       1 router.go:548] template "level"=0 "msg"="router reloaded"  "output"=" - Proxy protocol on, checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
E0106 19:12:50.664330       1 limiter.go:140] error reloading router: waitid: no child processes
 - Proxy protocol on, checking http://localhost:80 ...
 - Health check ok : 0 retry attempt(s).
```
from: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_router/77/pull-ci-openshift-router-master-e2e-aws/256/artifacts/e2e-aws/pods/openshift-ingress_router-default-7bc7f5dccd-5s7f6_router.log

**Comment by frobware** [comment]
failures (5): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/74/pull-ci-openshift-router-master-e2e-aws/273

/test e2e-aws

**Comment by frobware** [comment]
failures (5): https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/74/pull-ci-openshift-router-master-e2e-aws/274

/test e2e-aws

**Comment by frobware** [comment]
Testing 4.5 x haproxy-2.1.3 here: https://github.com/openshift/router/pull/92

**Pull request closed without merging**
