### PR TITLE
[release-4.8] Bug 1984565: config template: accept IPv6 IPs for whitelisting

### PR DESCRIPTION
**Pull request by alebedev87**
Manual backport of https://github.com/openshift/router/pull/307

### CODE REVIEW

**Comment by frobware** [comment]
For backport approval:

/assign @knobunc

**Comment by frobware** [comment]
> For backport approval:
> 
> /assign @knobunc

Actually, not needed here. Apologies. Will unassign.

**Comment by quarterpin** [comment]
/lgtm
/label qe-approved

Verified via pre-merge verification workflow, more references related to the test can be found in:
https://bugzilla.redhat.com/show_bug.cgi?id=1984565#c1

**Comment by alebedev87** [comment]
/retest-required

Monitoring stack problems: "Cluster operator monitoring is not available"

**Pull request merged**
