### PR TITLE
[WIP] - DO NOT MERGE - validate-haproxy22-2.2.22-1.el8.x86_64.rpm (4.11)

### PR DESCRIPTION
**Pull request by gcs278**
PR for soak testing haproxy22-2.2.22-1 (DO NOT MERGE)

### CODE REVIEW

**Comment by frobware** [comment]
Ignoring IPv6, CI was green.

/test all

**Comment by gcs278** [comment]
Test run #3?

/test all

**Comment by gcs278** [comment]
Bunch of operator unavailable issues. I don't think related to haproxy update.

Test run # 4 

/test all

**Comment by gcs278** [comment]
Lots of failures this time. I saw:
[sig-scheduling][Early] The HAProxy router pods should be scheduled on different nodes [Suite:openshift/conformance/parallel]

But highly doubt that is because of the haproxy version.

Test run # 6

/test all

**Comment by gcs278** [comment]
Cluster boot strap failed...again.

[sig-network][Feature:Router] The HAProxy router should run even if it has no access to update status [Skipped:Disconnected] [Suite:openshift/conformance/parallel]

Test run # 7

/test all

**Comment by gcs278** [comment]
The TRT tests look good to me, nothing related to haproxy.

Another failed cluster bootstrap. Not related to haproxy. I think look good.

Test run # 8

 /test all

**Comment by gcs278** [comment]
/retest

always cluster bootstrap should succeed on all of my PRs right now...

**Comment by gcs278** [comment]
I don't think any of these relate to haproxy.

/retest

**Comment by gcs278** [comment]
Haproxy 2.2.22 has been merged. Closing.

**Pull request closed without merging**
