### PR TITLE
OCPBUGS-38475: Rename router Dockerfiles

### PR DESCRIPTION
**Pull request by grzpiotrowski**
In an effort to fix the discrepancy between the Dockerfile names and their contents which refer to rhel9
Renamed Dockerfiles:
- from images/router/base/`Dockerfile.rhel` to images/router/base/`Dockerfile.ocp`
- from images/router/haproxy/`Dockerfile.rhel8` to images/router/haproxy/`Dockerfile.ocp`

which both are names independent of the version.

Coordinated with:
- merging the PR https://github.com/openshift/release/pull/55354 first.
- ART merging https://github.com/openshift-eng/ocp-build-data/pull/5265 once this is merged.

### CODE REVIEW

**Comment by grzpiotrowski** [comment]
/retest

https://github.com/openshift/release/pull/55354 merged, expecting tests to pass now.

**Review by alebedev87 — COMMENTED** [review]
Sorry, I noticed it a little late. Can you add the bug reference to the commit message too?

**Comment by grzpiotrowski** [comment]
> Sorry, I noticed it a little late. Can you add the bug reference to the commit message too?

Thank you. Bug reference added to the commit message now.

**Comment by alebedev87** [comment]
@grzpiotrowski : Thank you!

/lgtm
/approve

**Comment by ashwindasr** [comment]
/hold

Once all tests pass, I'll unhold so that we can get this and the coredns one in around the same time. Followed by https://github.com/openshift-eng/ocp-build-data/pull/5265

**Pull request merged**
