### PR TITLE
Refactor haproxy router config manager blueprint validation code.

### PR DESCRIPTION
**Pull request by ramr**
Follow up to refactor the blueprint validation code.

Migrated from: https://github.com/openshift/origin/pull/20722

### CODE REVIEW

**Comment by Miciah** [comment]
What's up with the return value of `AddBlueprint`? Was that change supposed to be in this PR? Should `(p *BlueprintPlugin) HandleRoute` be changed to handle the error return?

**Comment by ramr** [comment]
> What's up with the return value of `AddBlueprint`? Was that change supposed to be in this PR? 
> Should `(p *BlueprintPlugin) HandleRoute` be changed to handle the error return?
Missed that - good catch. Yeah, `HandleRoute` should propogate that error up.  So the old pr went thru' some iterations where it was generating events in here and then we dropped that, so the error handling needed to propogate errors back (on blueprint add).

**Comment by Miciah** [comment]
With `(p *BlueprintPlugin) HandleRoute` propagating the error from `AddBlueprint`, `(c *RouterController) processRoute` will log it, right? Do we still need the `glog.Errorf` in `AddBlueprint`?

**Comment by ramr** [comment]
> With `(p *BlueprintPlugin) HandleRoute` propagating the error from `AddBlueprint`, `(c *RouterController) processRoute` will log it, right? Do we still need the `glog.Errorf` in `AddBlueprint`?

I think it should - will check that next week and if so, remove it. Thx

**Comment by ramr** [comment]
@ironcladlou  PTAL needs approval. Thx

**Comment by knobunc** [comment]
@smarterclayton Do you know why this PR hates @Miciah and @ironcladlou?

/lgtm

**Comment by ramr** [comment]
/retest

error was: `level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to fetch dependency of \"Cluster ID\": failed to fetch dependency of \"Install Config\": failed to fetch dependency of \"Base Domain\": failed to generate asset \"Platform\": EOF"
�[0G�[2K�[1;92m? �[1;99mPlatform  [Use arrows to move, type to filter]`

**Pull request merged**
