### PR TITLE
Add Dockerfile.rhel8

### PR DESCRIPTION
**Pull request by yselkowitz**
A separate file is required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
This is net new.

**Comment by crawford** [comment]
From the [logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/155/pull-ci-openshift-router-master-images/1288199612259110912):
>  Downloading packages:
> http://base-4-6.ocp.svc/rhel-server-ose/Packages/haproxy-2.0.14-1.el7__x86_64/haproxy20-2.0.14-1.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found

**Comment by frobware** [comment]
> From the [logs](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_router/155/pull-ci-openshift-router-master-images/1288199612259110912):
> 
> > Downloading packages:
> > http://base-4-6.ocp.svc/rhel-server-ose/Packages/haproxy-2.0.14-1.el7__x86_64/haproxy20-2.0.14-1.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found

If this is for RHEL 8 shouldn't this pick up a .el8 rpm?

**Comment by frobware** [comment]
> If this is for RHEL 8 shouldn't this pick up a .el8 rpm?

We have a .el8 build here: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=1269195

**Comment by sdodson** [comment]
Those logs look like they're still from the rhel7 build. I think there needs to be a change to CI build infra to start realizing all of these changes.

**Comment by yselkowitz** [comment]
That will come once everything else is in place.

**Pull request merged**
