### PR TITLE
 [release-4.8] Bug 1971730: error pages - don't use bootstrap/normalize

### PR DESCRIPTION
**Pull request by alebedev87**
Manual cherry-pick of https://github.com/openshift/router/pull/300 ([robot cherry pick](https://github.com/openshift/router/pull/300#issuecomment-860787705) failed).

### CODE REVIEW

**Comment by Miciah** [comment]
Thanks!
/lgtm

**Comment by candita** [comment]
Can I do this?
/label group-lead-approved

**Pull request merged**
