### PR TITLE
[WIP] - DO NOT MERGE - validate-haproxy22-2.2.19-1.el8.x86_64.rpm (4.10)

### PR DESCRIPTION
**Pull request by frobware**
Soak test of haproxy-2.2.19. We plan to take this minor change in OCP-4.10. This PR serves as a soak test.

### CODE REVIEW

**Comment by frobware** [comment]
- level=error msg=Error: waiting for creation of Linux Virtual Machine "ci-op-ctv5029r-9c2de-lkh5r-bootstrap" (Resource Group "ci-op-ctv5029r-9c2de-lkh5r-rg"): Code="OSProvisioningTimedOut" Message="OS Provisioning for VM 'ci-op-ctv5029r-9c2de-lkh5r-bootstrap' did not finish in the allotted time."

/retest

**Comment by frobware** [comment]
CI was green. Testing again.

/test all

**Comment by frobware** [comment]
The purpose of this was a one-off verification before a perf & scale team run.

**Comment by frobware** [comment]
Fresh RPM build.

/test all

**Comment by petr-muller** [comment]
== Triggered 10 `ci-4.10:e2e-gcp-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=router-362-ci-4.10-e2e-gcp-upgrade
Aggregation ID: `950a4038-5838-11ec-a749-74d435fb2dc0

**Comment by deads2k** [comment]
```
CGO_ENABLED=0 go build github.com/openshift/ci-tools/cmd/job-run-aggregator && ./job-run-aggregator analyze-job-runs --google-service-account-credential-file='/home/deads/openshift-ci-bigquery-credentials.json' --explicit-gcs-prefix=logs/router-362-ci-4.10-e2e-gcp-upgrade  --job=periodic-ci-openshift-release-master-ci-4.10-e2e-gcp-upgrade --aggregation-id=950a4038-5838-11ec-a749-74d435fb2dc0 --job-start-time=2021-12-08T14:07:55Z
```

Shows good aggregation results.

**Comment by frobware** [comment]
Closing as the associated change https://pkgs.devel.redhat.com/cgit/rpms/haproxy/commit/?h=rhaos-4.10-rhel-8 has merged.

**Pull request closed without merging**
